name: Get News & Generate Keywords V0.1

on:
  schedule:
    - cron: '1 6 * * *'
  workflow_dispatch: 

env:
  TZ: "Europe/London"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  updatecsv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas newsapi openai
        
    - name: Run NEWSAPI Python script
      env:
        NEWSAPI_API_KEY: ${{ secrets.NEWSAPI_API_KEY }}
      run: |
        python script/get_news.py
        
    - name: Commit news change
      run: |
        git config --global user.email "leungw3@cardiff.ac.uk"
        git config --global user.name "LLeung"
        git add .
        git commit -m "Update news main.csv"
    - name: Push news change
      run: |
        git push
  
    - name: Run OPENAI Python script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        python script/generate_keywords.py
        
    - name: Commit and push changes
      run: |
        git config --global user.email "leungw3@cardiff.ac.uk"
        git config --global user.name "LLeung"
        git add .
        git commit -m "Update keywords main.csv"

    - name: Push keywords change
      run: |
        git push

    - name: Create artifact
      uses: actions/upload-artifact@v3
      with:
        name: updated-news-keywords
        path: /web/data  
        
  deploy:
    needs: updatecsv
    runs-on: ubuntu-latest
    
    steps:          
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: get-updated-news-keywords
          path: './web'
        
      - name: Upload artifact to page
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './web'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
